# Generated by Django 4.2.26 on 2025-11-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=100)),
                ('translate_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'category_news',
                'db_table': 'Category_News',
            },
        ),
        migrations.CreateModel(
            name='News_Avicenna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('translate_title', models.CharField(blank=True, max_length=100, null=True)),
                ('picture_1', models.FileField(blank=True, null=True, upload_to='')),
                ('picture_2', models.FileField(blank=True, null=True, upload_to='')),
                ('picture_3', models.FileField(blank=True, null=True, upload_to='')),
                ('picture_4', models.FileField(blank=True, null=True, upload_to='')),
                ('body', models.TextField(blank=True, null=True)),
                ('translate_body', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='news.category_news')),
            ],
            options={
                'verbose_name_plural': 'news_avicenna',
                'db_table': 'News_Avicenna',
            },
        ),
    ]
