# Generated by Django 4.2.26 on 2025-11-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Slider',
            new_name='Slider_Picture',
        ),
        migrations.AlterModelOptions(
            name='slider_picture',
            options={'verbose_name_plural': 'slider_picture'},
        ),
        migrations.AlterModelTable(
            name='slider_picture',
            table='slider_picture',
        ),
    ]
