# Generated by Django 4.2.26 on 2025-11-29 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_rename_slider_slider_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider_picture',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to=settings.AUTH_USER_MODEL),
        ),
    ]
